<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationTitle>Generator haseł</ApplicationTitle>
    <RootNamespace>GeneratorHasel</RootNamespace>
    <AssemblyName>GeneratorHasel</AssemblyName>
  </PropertyGroup>
</Project>
